workflows:
    
    flutter-widget:
        name: Flutter Widget
        instance_type: linux_x2
        max_build_duration: 120
        environment:
            flutter: stable
        scripts:
            - sudo apt-get update
            - sleep 9999
